name: Release

on:
    workflow_dispatch:
        inputs:
            release-type:
                description: "What kind of release is this?"
                type: choice
                options:
                    - alpha
                    - rc
                    - final
                required: true

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash --noprofile --norc -euo pipefail {0}

# wants to push commits and create a PR
permissions: write-all

jobs:
    # NOTE: When updating this job, also remember to update `post-release-version-bump`.
    version:
        name: "Versioning"
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get-version.outputs.version }}
            previous: ${{ steps.versioning.outputs.previous }}
            current: ${{ steps.versioning.outputs.current }}
            final: ${{ steps.versioning.outputs.final }}
            git_tag: ${{ steps.versioning.outputs.git_tag }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"

            - uses: astral-sh/setup-uv@v6

            - name: Install dependencies
              run: uv sync --dev

            - name: Get and validate version
              id: get-version
              run: |
                  output=$(uv run python scripts/ci/version.py get-version)
                  echo "$output"
                  version=$(echo "$output" | grep "Release version:" | cut -d' ' -f3)
                  echo "version=$version" >> $GITHUB_OUTPUT

            - name: Update versions
              id: versioning
              run: |
                  uv run python scripts/ci/version.py set-version ${{ steps.get-version.outputs.version }}
