name: Run release from branch
on: push
jobs:
    run:
        uses: ./.github/workflows/release.yml
        with:
            release-type: final
        secrets: inherit

defaults:
    run:
        shell: bash --noprofile --norc -euo pipefail {0}

# wants to push commits and create a PR
permissions: write-all
